{% set name = "ampl-asl" %}
{% set version = "1.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ampl/asl/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 57b767161fd95869757daa0761d9b19fa39ad5de4315f95a3c0dff08b0d4c4f2
  patches:
    # Backport https://github.com/ampl/asl/pull/22
    - 22.patch
    # Ensure that .dll gets installed in <CMAKE_INSTALL_PREFIX>/bin
    - install_library_in_default_location.patch
    - disable_setting_custom_flags_in_arm_and_ppc.patch

build:
  number: 0
  run_exports:
    # No ABI policy documented
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  run_constrained:
    # Earlier version of ampl-mp package vendored ampl-asl,
    # and so we need to prevent that they are installed together
    # to avoid clobbering
    # see https://github.com/conda-forge/ampl-mp-feedstock/issues/25
    - ampl-mp >=4.0.0

test:
  commands:
    - test -f ${PREFIX}/include/asl/asl.h  # [not win]
    - test -f ${PREFIX}/lib/libasl${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\include\\asl\\asl.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\asl.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\asl.dll exit 1  # [win]
    - cmake-package-check ampl-asl
  requires:
    - cmake-package-check
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://github.com/ampl/asl
  license: BSD-3-Clause AND SMLNJ
  license_file:
    - LICENSE
    - src/f2c/Notice
  summary: ASL (AMPL Solver Library).

extra:
  feedstock-name: ampl-asl
  recipe-maintainers:
    - traversaro
